WIP: Add HTTP to gRPC auth. credential forwarding
buildbarn/bb-browser pull request #7
Opened 2019-03-18 16:40 UTC by t-chaik

See discussion at https://github.com/buildbarn/bb-browser/issues/5.

2019-03-18 16:56 UTC, EdSchouten requested changes
Awesome!

2019-03-18 16:56 UTC, EdSchouten commented on cmd/bb_browser/browser_service.go
> +	if req.Header.Get("Authorization") != "" {
```go
if authorization := req.Header.Get("Authorization"); authorization != "" {
    md.Set("authorization", authorization)
}
```

2019-03-18 16:56 UTC, EdSchouten commented on cmd/bb_browser/browser_service.go
> +func extractContextFromRequest(req *http.Request) context.Context {
Could you add a comment above this function to explain what it does/what the purpose is?

2019-03-19 09:42 UTC, t-chaik commented
Updated following your review advices.

2019-03-19 14:02 UTC, merged